# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qik_test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eqik_test.proto\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x02\"\x18\n\x08Response\x12\x0c\n\x04name\x18\x01 \x01(\t2)\n\x07Quantam\x12\x1e\n\x06\x63ircut\x12\x07.Number\x1a\t.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qik_test_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NUMBER._serialized_start=18
  _NUMBER._serialized_end=41
  _RESPONSE._serialized_start=43
  _RESPONSE._serialized_end=67
  _QUANTAM._serialized_start=69
  _QUANTAM._serialized_end=110
# @@protoc_insertion_point(module_scope)
