# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import qik_test_pb2 as qik__test__pb2


class QuantamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.circut = channel.unary_unary(
                '/Quantam/circut',
                request_serializer=qik__test__pb2.Number.SerializeToString,
                response_deserializer=qik__test__pb2.Response.FromString,
                )


class QuantamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def circut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuantamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'circut': grpc.unary_unary_rpc_method_handler(
                    servicer.circut,
                    request_deserializer=qik__test__pb2.Number.FromString,
                    response_serializer=qik__test__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Quantam', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Quantam(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def circut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Quantam/circut',
            qik__test__pb2.Number.SerializeToString,
            qik__test__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
